# Generated by Django 3.2.5 on 2021-07-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postimage', '0002_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./image/'),
        ),
    ]
