# Generated by Django 3.2.5 on 2021-07-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postimage', '0006_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
