# Generated by Django 3.2.5 on 2021-07-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postimage', '0007_auto_20210718_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='tag',
            field=models.TextField(null=True),
        ),
    ]
