# Generated by Django 3.2.5 on 2021-07-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postimage', '0008_auto_20210718_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
