# Generated by Django 3.2.5 on 2021-07-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postimage', '0009_alter_photo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
