# Generated by Django 3.2.5 on 2021-07-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postimage', '0010_photo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
